### ISSUE TITLE
数据库连接字符串是？

### ISSUE THREAD

**Issue by yaobo-lab** [china-live/XCore#6]
数据库连接字符串是？怎样的。使用的是MSSQL？ 能否给个连接字符串示例。报错呢

**Comment by yaobo-lab** [comment]
![c01dad19da642f261096b6fc91462fc](https://user-images.githubusercontent.com/21329253/80276719-053e6d00-871d-11ea-822a-53d02d5ffd96.png)

调试报这个错

**Comment by yaobo-lab** [comment]
![微信图片_20200425174923](https://user-images.githubusercontent.com/21329253/80276729-1f784b00-871d-11ea-8d21-6e7b02467e28.png)

**Comment by ldming-com** [comment]
连接字符串是标准的.net调用MSSQL方式，比如：Server=.;Database=OCoreDb;UID=sa;PWD=1234567890;MultipleActiveResultSets=true
这个连接字符串并不是在部署程序时配置的，而是在第一次启动访问时在页面中配置默认租户的运行环境（由OCore.Setup处理），包括数据库类型、连接字符串和RequestUrlHost（为每个租户分配一个二级域名或路径）， OCore.Mvc.Web内ConnectionString也仅仅是为了EF DbContext占个坑而已，当然，它不是必须的，你可以自己实现用别的模块访问数据库。

**Comment by yaobo-lab** [comment]
在第一次启动访问时在页面中配置。我使的就是这个连接字符串：
Server=.;Database=OCoreDb;UID=sa;PWD=1234567890;MultipleActiveResultSets=true
发现报上面截图的错。你能正常运行？

**Comment by ldming-com** [comment]
Ambiguous match found. 应该是.net引用的程序集有变动，你拉下来源码先不要做任何更新再运行看看。

**Comment by yaobo-lab** [comment]
> Ambiguous match found. 应该是.net引用的程序集有变动，你拉下来源码先不要做任何更新再运行看看。

你说的是任何 更新是指什么?.我就是直接下载 完源代码。运行。出现初始配置页面。然后填内容点击无反应在。然后debug进去发现。出错。
